version: "3.9"

services:
  db:
    image: postgres:16
    container_name: shop-db
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shop"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: shop-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10

  payment:
    build:
      context: ./payment
      dockerfile: Dockerfile
    container_name: shop-payment
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://db:5432/shop
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: postgres

      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shop
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  main:
    build:
      context: ./main
      dockerfile: Dockerfile
    container_name: shop-main
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      payment:
        condition: service_started
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://db:5432/shop
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shop
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      PAYMENT_BASE_URL: http://payment:8081

      REDIS_HOST: redis
      REDIS_PORT: 6379

volumes:
  postgres_data: