spring:
  application:
    name: shop
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}


  liquibase:
    enabled: true

server:
  port: 8080
  address: 0.0.0.0


logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql: DEBUG
