spring:
  application:
    name: shop
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: shop-app
            client-secret: 5r6RiXMyRitSG8YF2b7bKzMb74SKyNUu
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/shop-app

  data:
    redis:
      host: localhost
      port: 6379
  #  data:
  #    redis:
  #      host: ${REDIS_HOST:redis}
  #      port: ${REDIS_PORT:6379}


  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    url: ${SPRING_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

server:
  port: 8080
  address: 0.0.0.0


logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql: DEBUG
    org.springframework.security: DEBUG
    liquibase: DEBUG

main:
  uploads-path: uploads/

payment:
  base-url: http://localhost:8081